=== Markela-prog/Saityno-paslaugos-1pd/casino.dtd
<!ELEMENT casino (id, games, players)>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT games (game+)>
        <!ELEMENT game (id, name, description, rules, minBet, maxBet)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT rules (#PCDATA)>
        <!ELEMENT minBet (#PCDATA)>
        <!ELEMENT maxBet (#PCDATA)>
        <!ELEMENT players (player+)>
        <!ELEMENT player (id, name, account)>
        <!ELEMENT account (id, email, password, age, balance, credits, transactions, bets)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT password (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT balance (#PCDATA)>
        <!ELEMENT credits (#PCDATA)>
        <!ELEMENT transactions (transaction+)>
        <!ELEMENT transaction (id, transactionType, amount)>
        <!ELEMENT transactionType (#PCDATA)>
        <!ELEMENT amount (#PCDATA)>
        <!ELEMENT bets (bet+)>
        <!ELEMENT bet (id, betAmount, outcome)>
        <!ELEMENT betAmount (#PCDATA)>
        <!ELEMENT outcome (#PCDATA)>

=== Markela-prog/Saityno-paslaugos-1pd/generated.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE casino SYSTEM "casino.dtd">
<casino>
    <id>1</id>
    <games>
        <game xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="roulette">
            <id>3</id>
            <name>Roulette</name>
            <description>desc</description>
            <rules>rules</rules>
            <minBet>0.1</minBet>
            <maxBet>1000.0</maxBet>
        </game>
        <game>
            <id>1</id>
            <name>Blackjack</name>
            <description>desc</description>
            <rules>rules</rules>
            <minBet>0.5</minBet>
            <maxBet>100.0</maxBet>
        </game>
        <game>
            <id>2</id>
            <name>Poker</name>
            <description>desc</description>
            <rules>rules</rules>
            <minBet>1.0</minBet>
            <maxBet>1000.0</maxBet>
        </game>
    </games>
    <players>
        <player>
            <id>1</id>
            <name>ProfileName1</name>
            <account>
                <id>1</id>
                <email>1@gmail.com</email>
                <password>password1</password>
                <age>20</age>
                <balance>610.0</balance>
                <credits>0</credits>
                <transactions>
                    <transaction>
                        <id>0</id>
                        <transactionType>deposit</transactionType>
                        <amount>500.0</amount>
                    </transaction>
                    <transaction>
                        <id>0</id>
                        <transactionType>deposit</transactionType>
                        <amount>20.0</amount>
                    </transaction>
                    <transaction>
                        <id>0</id>
                        <transactionType>withdrawal</transactionType>
                        <amount>10.0</amount>
                    </transaction>
                </transactions>
                <bets>
                    <bet>
                        <id>1</id>
                        <betAmount>100.0</betAmount>
                        <outcome>Win</outcome>
                    </bet>
                    <bet>
                        <id>2</id>
                        <betAmount>100.0</betAmount>
                        <outcome>Lose</outcome>
                    </bet>
                </bets>
            </account>
        </player>
        <player>
            <id>1</id>
            <name>ProfileName2</name>
            <account>
                <id>1</id>
                <email>2@gmail.com</email>
                <password>password2</password>
                <age>22</age>
                <balance>200.0</balance>
                <credits>10</credits>
                <transactions>
                    <transaction>
                        <id>0</id>
                        <transactionType>deposit</transactionType>
                        <amount>100.0</amount>
                    </transaction>
                    <transaction>
                        <id>0</id>
                        <transactionType>withdrawal</transactionType>
                        <amount>150.0</amount>
                    </transaction>
                </transactions>
                <bets>
                    <bet>
                        <id>3</id>
                        <betAmount>50.0</betAmount>
                        <outcome>Win</outcome>
                    </bet>
                    <bet>
                        <id>4</id>
                        <betAmount>100.0</betAmount>
                        <outcome>Lose</outcome>
                    </bet>
                </bets>
            </account>
        </player>
    </players>
</casino>
